name: build CI

on:
    push:
        branches: main
    workflow_dispatch:
    workflow_call:

jobs:
    build:
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-22.04]
                builder: ['pyinstaller']
        runs-on: ${{matrix.os}}
        steps:
        - uses: actions/checkout@v4
        - name: Setup Python
          uses: actions/setup-python@v5
          with:
            python-version: 3.11
            cache: 'pip' 
            cache-dependency-path: '**/requirements.txt'
        - name: Install dependencies
          run: pip install -r requirements.txt
        - name: build with pyinstaller
          if: ${{matrix.builder == 'pyinstaller'}}
          run: |
            pip install pyinstaller
            cd src/payload_dumper
            pyinstaller -F __main__.py
        - name: Build with nuitka
          if: ${{matrix.builder == 'nuitka'}}
          run: |
            sudo apt-get install ccache
            pip install nuitka
            python3 -m nuitka --onefile --standalone --show-progress --remove-output --output-dir=dist patcher.py
            
        - name: Upload
          uses: actions/upload-artifact@v4
          with: 
            name: build-${{matrix.os}}-${{matrix.builder}}
            path: ./src/payload_dumper/dist